const enLabels = {
  "User": {
    "email": "Email",
    "phone": "Phone",
    "code": "Code",
    "password": "Password",
    "mailcodesuccess": "A verification code has been sent",
    "loginsuccess": "Log in succeeded",
    "sysfail": "System fail",
    "logintitle": "Log In",
    "logintitletip1": "By continuing, you agree to our ",
    "logintitletip2": "User Agreement",
    "logintitletip3": "and",
    "logintitletip4": "Privacy Policy",
    "logintitletip5": ".",
    "loginsubmitbtn": "Verify and log in",
    "loginphonebtn": "Phone Log In",
    "loginemailbtn": "Email Log In",
    "loginothermethods": "Other methods",
    "loginforgotpassword": "Forgot password?",
    "loginsignuptitle": "New to DDream.LAND? ",
    "loginsignuplink": "Sign Up",
    "loginvctip": "Unable to receive verification code, password login",
    "loginpwtip": "Verification code login",
    "loginenterpassword": "Enter password",
    "loginentercode": "Enter verification code",
    "edituserinfosuccess": "Save succeeded"
  },
  "UserRegister": {
    "title": "Sign Up",
    "send": "Send",
    "submit": "Sign Up",
    "verification": "Verification",
    "phonebtn": "Phone Sign Up",
    "emailbtn": "Email Sign Up",
    "othermethods": "Other methods",
    "logintitle": "Already a DDreamer",
    "loginlink": "Log In",
    "phoneverifycodetip1": "Input code",
    "phoneverifycodetip2": "A 5-digit verification code has been sent to",
    "phoneregetcode": "Get the verification code again",
    "phoneregetcodecountdown": "seconds, Get the verification code again",
    "phonepwtitle": "Set password",
    "phonepwtip": "For the security of your account, please set a password for your account",
    "phonepwsubmitbtn": "Register account",
    "success": "DDream.Land account created successfully!",
  },
  "UserResetPassword": {
    "title": "Reset Password",
    "send": "Send",
    "submit": "Reset",
    "success": "Password changed successfully!",
    "othermethods": "Other methods",
    "phonebtn": "Phone Reset Password",
    "emailbtn": "Email Reset Password",
    "phonepwtitle": "Set password",
    "phonepwtip": "",
    "phonepwsubmitbtn": "Reset Password",
  },
  "UserDeleteUser": {
    "title": "Account cancellation",
    "send": "Send",
    "submit": "Cancel",
    "success": "DDream.Land account cancellation successfully!",
    "othermethods": "Other methods",
    "phonebtn": "Phone Cancellation",
    "emailbtn": "Email Cancellation",
    "phonepwtitle": "Set password",
    "phonepwtip": "",
    "phonepwsubmitbtn": "Account cancellation",
  },
  "UserFormSchema": {
    "email": "Invalid email format, please check your email address.",
    "password": "Password must be at least 6 characters.",
    "code": "Incorrect verification code, please check the code."
  }
}

export default enLabels;