const zhCNLabels = {
  "User": {
    "email": "邮箱",
    "phone": "手机号",
    "code": "验证码",
    "password": "密码",
    "mailcodesuccess": "发送验证码成功",
    "loginsuccess": "DDream.Land 登录成功",
    "sysfail": "系统报错",
    "logintitle": "登录",
    "logintitletip1": "继续即表示您理解并同意我们的",
    "logintitletip2": "用户协议",
    "logintitletip3": "和",
    "logintitletip4": "隐私政策",
    "logintitletip5": ".",
    "loginsubmitbtn": "验证并登录",
    "loginphonebtn": "手机号登录",
    "loginemailbtn": "邮箱登录",
    "loginothermethods": "其他方式登录",
    "loginforgotpassword": "忘记密码?",
    "loginsignuptitle": "新的 DDream.LAND? ",
    "loginsignuplink": "注册",
    "loginvctip": "无法收到验证码，密码登录",
    "loginpwtip": "验证码登录",
    "loginenterpassword": "输入密码",
    "loginentercode": "输入验证码",
    "edituserinfosuccess": "保存成功"
  },
  "UserRegister": {
    "title": "注册",
    "send": "发送验证码",
    "submit": "注册",
    "verification": "验证",
    "phonebtn": "手机号注册",
    "emailbtn": "邮箱注册",
    "othermethods": "其他方式注册",
    "logintitle": "已有 DDream.LAND?",
    "loginlink": "登录",
    "phoneverifycodetip1": "输入验证码",
    "phoneverifycodetip2": "已发送 5 位验证码至",
    "phoneregetcode": "重新获取验证码",
    "phoneregetcodecountdown": "秒后重新获取验证码",
    "phonepwtitle": "设置密码",
    "phonepwtip": "为了您的账号安全，请给您的账号设置一个密码",
    "phonepwsubmitbtn": "注册账号",
    "success": "DDream.Land 注册成功",
  },
  "UserResetPassword": {
    "title": "修改密码",
    "send": "发送验证码",
    "submit": "修改",
    "success": "修改密码成功",
    "othermethods": "其他方式",
    "phonebtn": "手机号修改密码",
    "emailbtn": "邮箱修改密码",
    "phonepwtitle": "设置密码",
    "phonepwtip": "",
    "phonepwsubmitbtn": "修改密码",
  },
  "UserDeleteUser": {
    "title": "注销账户",
    "send": "发送验证码",
    "submit": "注销",
    "success": "注销账户成功",
    "othermethods": "其他方式",
    "phonebtn": "手机号注销账户",
    "emailbtn": "邮箱注销账户",
    "phonepwtitle": "设置密码",
    "phonepwtip": "",
    "phonepwsubmitbtn": "注销账户",
  },
  "UserFormSchema": {
    "email": "邮箱格式错误，请检查你的邮箱地址",
    "password": "密码最短6位",
    "code": "验证码错误"
  }
}

export default zhCNLabels;